### ISSUE TITLE
add require(magrittr) to slim() function

### ISSUE THREAD

**Issue by nickreich** [aaronger/alloscore#4]
https://github.com/aaronger/alloscore/blob/7baef02a6d772fa407588f4528734ac8cfaeb4f3/R/allocation.R#L381

I loaded alloscore but nothing else and got this error.

```
> library(alloscore)
> ?slim
> slim(alloscore_USC.SI_kJalpha_2022.02.21)
Error in adf %>% select(tidyselect::any_of(id_cols)) : 
  could not find function "%>%"
```

**Comment by nickreich** [comment]
maybe it should be listed as a dependency in description as well.

**Comment by aaronger** [comment]
Yes - unfortunately I've found `|>` to lack some of `%>%`'s conveniences...

**Comment by aaronger** [comment]
done... months later 668baaa
